// Finds a real email address for a named person at a company.
//
// This is the step Jesse cares most about: a draft addressed to nobody is a
// draft he has to finish by hand. The rule that does not bend is that a guessed
// address is never presented as a found one. Every result carries a confidence
// and the evidence behind it, so the summary email can tell him which addresses
// are safe to send blind and which want a glance first.
//
// Confidence levels:
//   "verified" - the address was read off a page, and its local part matches
//                the person's name
//   "role"     - a real published address, but a shared inbox (press@, hello@),
//                so the salutation carries the person's name and the mail goes
//                to a desk rather than to them
//   "pattern"  - constructed from the person's name using an address shape seen
//                at least twice at that domain. Plausible, not confirmed.
//   null       - nothing found. Draft goes out with an empty To: line.
//
// NETWORK: this module needs to reach arbitrary company websites. It cannot run
// inside the Claude Code sandbox, whose egress proxy allows only an allowlist.
// Run it from the Vercel deployment, or anywhere with open outbound HTTPS, and
// pass in a fetch implementation.

const ROLE_LOCAL_PARTS = new Set([
  "info", "hello", "hi", "hey", "contact", "support", "help", "admin", "team",
  "press", "pr", "media", "news", "sales", "careers", "jobs", "recruiting",
  "legal", "privacy", "security", "abuse", "dmca", "compliance", "billing",
  "accounts", "accounting", "ir", "investors", "partners", "hr", "people",
  "noreply", "no-reply", "donotreply", "mailer-daemon", "postmaster", "webmaster",
]);

// Ordered by how much a hit tells us. Contact and team pages name people;
// privacy and terms pages almost always carry a real monitored address.
const CANDIDATE_PATHS = [
  "/", "/contact", "/contact-us", "/about", "/about-us", "/team", "/our-team",
  "/leadership", "/company", "/people", "/press", "/newsroom", "/media",
  "/privacy", "/privacy-policy", "/legal", "/terms", "/terms-of-service",
];

const EMAIL_RE = /[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}/g;

/**
 * The registrable-ish domain for matching. Strips a leading "www." only; we
 * want subdomain mail (press@news.example.com) to count as the same company.
 * @param {string} url
 * @returns {string|null}
 */
function siteDomain(url) {
  try {
    return new URL(url).hostname.replace(/^www\./i, "").toLowerCase();
  } catch {
    return null;
  }
}

/**
 * Pull every address on the page that belongs to the company's own domain.
 * Third-party addresses (the PR agency, the hosting provider) are noise here.
 * @param {string} html
 * @param {string} domain
 * @returns {string[]} lowercased, de-duplicated
 */
function extractEmails(html, domain) {
  const found = String(html || "").match(EMAIL_RE) || [];
  const suffix = String(domain || "").toLowerCase();
  const seen = new Set();
  for (const raw of found) {
    const addr = raw.toLowerCase().replace(/[.,;:)]+$/, "");
    const host = addr.split("@")[1];
    if (!host) continue;
    if (host === suffix || host.endsWith("." + suffix)) seen.add(addr);
  }
  return [...seen];
}

function localPart(addr) {
  return String(addr).split("@")[0].toLowerCase();
}

function isRoleAddress(addr) {
  return ROLE_LOCAL_PARTS.has(localPart(addr));
}

/**
 * Split a display name into lowercased ascii first and last tokens.
 * Accents are folded, because address local parts rarely carry them: Zoë Weil
 * is zoe.weil@, not zoë.weil@.
 * @param {string} name
 * @returns {{first: string, last: string}|null}
 */
function nameParts(name) {
  const cleaned = String(name || "")
    .normalize("NFD")
    .replace(/[̀-ͯ]/g, "")
    .replace(/[^A-Za-z\s'-]/g, " ")
    .trim();
  const tokens = cleaned.split(/\s+/).filter(Boolean);
  if (tokens.length < 2) return null;
  return {
    first: tokens[0].toLowerCase().replace(/[^a-z]/g, ""),
    last: tokens[tokens.length - 1].toLowerCase().replace(/[^a-z]/g, ""),
  };
}

const SHAPES = {
  "first.last": (p) => `${p.first}.${p.last}`,
  "first_last": (p) => `${p.first}_${p.last}`,
  "firstlast": (p) => `${p.first}${p.last}`,
  "flast": (p) => `${p.first[0]}${p.last}`,
  "f.last": (p) => `${p.first[0]}.${p.last}`,
  "first": (p) => p.first,
};

/**
 * Does this local part look like it was generated by `shape` for this person?
 * @returns {boolean}
 */
function matchesShape(local, shape, parts) {
  const build = SHAPES[shape];
  return !!build && build(parts) === local;
}

/**
 * Which shapes is a local part consistent with, given no knowledge of whose it
 * is? Used to infer a company's convention from other people's addresses.
 * Single-token locals are deliberately NOT reported as "first", because
 * "jsmith" and "john" are indistinguishable without knowing the owner.
 * @param {string} local
 * @returns {string[]}
 */
function shapesConsistentWith(local) {
  const out = [];
  if (/^[a-z]+\.[a-z]+$/.test(local)) out.push("first.last");
  if (/^[a-z]_[a-z]+$/.test(local) || /^[a-z]+_[a-z]+$/.test(local)) out.push("first_last");
  if (/^[a-z]\.[a-z]{2,}$/.test(local)) out.push("f.last");
  return out;
}

/**
 * Infer the company's address convention from personal addresses seen on its
 * own pages. Requires at least two agreeing samples: one is a coincidence.
 * @param {string[]} addresses
 * @returns {{shape: string, basis: string[]}|null}
 */
function inferShape(addresses) {
  const personal = (addresses || []).filter((a) => !isRoleAddress(a));
  const tally = new Map();
  for (const addr of personal) {
    for (const shape of shapesConsistentWith(localPart(addr))) {
      if (!tally.has(shape)) tally.set(shape, []);
      tally.get(shape).push(addr);
    }
  }
  let best = null;
  for (const [shape, basis] of tally) {
    if (basis.length < 2) continue;
    if (!best || basis.length > best.basis.length) best = { shape, basis };
  }
  return best;
}

/**
 * Look for a person's address at their company.
 *
 * @param {object} opts
 * @param {string} opts.website  company URL from the digest
 * @param {string} opts.personName  full name, e.g. "Alex Hejnosz"
 * @param {function} opts.fetchImpl  async (url) => ({ok, text()}); inject the
 *   platform's fetch. Required, so this stays testable and so the caller
 *   controls timeouts and user agent.
 * @param {string[]} [opts.extraPages]  additional URLs worth reading, such as
 *   the funding press release, which usually ends in a media contact block
 * @param {number} [opts.pageTimeoutMs]  per-request timeout, default 8000. One
 *   unresponsive host must not consume the caller's whole time budget.
 * @param {number} [opts.deadline]  Date.now() value past which no further
 *   pages are fetched
 * @returns {Promise<{email: string|null, confidence: string|null, evidence: string[], notes: string[]}>}
 */
async function findEmail({
  website,
  personName,
  fetchImpl,
  extraPages = [],
  pageTimeoutMs = 8000,
  deadline = null,
}) {
  const domain = siteDomain(website);
  const parts = nameParts(personName);
  const notes = [];
  const evidence = [];

  if (!domain) return { email: null, confidence: null, evidence, notes: ["no usable website"] };
  if (!fetchImpl) throw new TypeError("findEmail requires a fetchImpl");

  const urls = [
    ...CANDIDATE_PATHS.map((p) => new URL(p, website).toString()),
    ...extraPages,
  ];

  const collected = new Set();
  for (const url of urls) {
    if (deadline && Date.now() > deadline) {
      notes.push("stopped sweeping early, out of time");
      break;
    }
    let html;
    try {
      // AbortSignal.timeout is Node 18+; fall back to no signal so an injected
      // test fetch, or an older runtime, still works.
      const signal =
        typeof AbortSignal !== "undefined" && AbortSignal.timeout
          ? AbortSignal.timeout(pageTimeoutMs)
          : undefined;
      const res = await fetchImpl(url, signal ? { signal } : undefined);
      if (!res || !res.ok) continue;
      html = await res.text();
    } catch {
      continue;
    }
    const hits = extractEmails(html, domain);
    if (hits.length) evidence.push(url);
    for (const h of hits) collected.add(h);
  }

  const addresses = [...collected];
  if (!addresses.length) {
    return { email: null, confidence: null, evidence, notes: ["no addresses published on the site"] };
  }

  // 1. An address that is demonstrably this person's.
  if (parts) {
    for (const addr of addresses) {
      const local = localPart(addr);
      for (const shape of Object.keys(SHAPES)) {
        if (matchesShape(local, shape, parts)) {
          return { email: addr, confidence: "verified", evidence, notes };
        }
      }
    }
  }

  // 2. Their convention applied to this person's name.
  if (parts) {
    const inferred = inferShape(addresses);
    if (inferred) {
      const candidate = `${SHAPES[inferred.shape](parts)}@${domain}`;
      notes.push(
        `constructed as ${inferred.shape} from the pattern at ${domain}, seen in ` +
          inferred.basis.join(" and ")
      );
      return { email: candidate, confidence: "pattern", evidence, notes };
    }
    notes.push("no repeated address pattern to infer from");
  }

  // 3. A real desk that will read it, with the person named in the salutation.
  const role = addresses.find(isRoleAddress);
  if (role) {
    notes.push("shared inbox, not the person directly");
    return { email: role, confidence: "role", evidence, notes };
  }

  return { email: null, confidence: null, evidence, notes };
}

module.exports = {
  findEmail,
  extractEmails,
  inferShape,
  nameParts,
  siteDomain,
  isRoleAddress,
  shapesConsistentWith,
  CANDIDATE_PATHS,
};
